[webservers]
web01 ansible_host=3.39.229.27
web02 ansible_host=3.35.16.236

[dbservers]
db01 ansible_host=172.20.32.232 ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -i ../terraform/my-key.pem -W %h:%p -q ec2-user@3.39.229.27"'
